reports/urls.py
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view
)

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='reportmain'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('from_file/', UploadTemplateView.as_view(), name='from-file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf'),
]

reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SaleListView,
    SaleDetailView
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SaleListView.as_view(), name='list'),
    path('sales/<pk>', SaleDetailView.as_view(), name='detail'),

]

reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse


# Create your models here.
class Report(models.Model):
    ''' Report can consist many sales object. '''
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('-created',)

reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

reports/views.py
from django.shortcuts import render, get_object_or_404
from profiles.models import Profile
from django.http import JsonResponse
from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, DetailView, TemplateView
from .forms import ReportForm

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from sales.models import Sale, Position, CSV
from products.models import Product
from customers.models import Customer
import csv
from django.utils.dateparse import parse_date

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/main.html'


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'


class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'


@login_required
def csv_upload_view(request):
    print('file is being sent')

    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)

        if created:
            obj.csv_file = csv_file
            obj.save()

            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__()
                for row in reader:
                    data = "".join(row)
                    data = data.split(';')
                    data.pop()

                    transaction_id = data[1]
                    product = data[2]
                    quantity = int(data[3])
                    customer = data[4]
                    date = parse_date(data[5])

                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    except Product.DoesNotExist:
                        product_obj = None

                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(
                            name=customer)
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(
                            product=product_obj, quantity=quantity, created=date)

                        sale_obj, _ = Sale.objects.get_or_create(
                            transaction_id=transaction_id, customer=customer_obj, salesman=salesman_obj, created=date)
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()
                return JsonResponse({'ex': False})
        else:
            return JsonResponse({'ex': True})

    return HttpResponse()


def create_report_view(request):
    form = ReportForm(request.POST or None)
    if request.is_ajax():
        # name = request.POST.get('name')
        # remarks = request.POST.get('remarks')
        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(user=request.user)
        # Report.objects.create(name=name, remarks=remarks, image=img, author=author)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.image = img
            instance.author = author
            instance.save()

        return JsonResponse({'msg': 'send'})
    return JsonResponse({})


@login_required
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj': obj}

    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="report.pdf"'

    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
        html, dest=response)

    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

reports/templates/reports/detail.html
{% extends "base.html" %}

<!-- Add title -->
{% block title %} {{object.name}} {% endblock title %}

<!-- Add block content -->
{% block content %}
<!-- Add object image -->
{% if object.image %}
<img src="{{object.image.url}}" class="img-fluid" alt="{{object.name}}" />
{% endif %}

<br />
<h3>Remarks</h3>
<p>{{object.remarks}}</p>
<hr />
<p>author: <b>{{object.author.user.username}}</b></p>
<p>created: <b>{{object.created}}</b></p>
{% endblock content %}

reports/templates/reports/from_file.html
{% extends "base.html" %}
<!-- Load Static files -->
{% load static %}

<!-- Load scripts -->
{% block scripts %}
<script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

<!-- Load titles -->
{% block title %} upload sales files {% endblock title %}

<!-- Load Content -->
{% block content %}
<h5>Upload your sales documents</h5>
<br />
<div id="alert-box"></div>
<form id="my-dropozne" class="dropzone dz">
  {% csrf_token %}
  <div class="fallback">
    <input name="file" type="file" multiple />
  </div>
</form>

{% endblock content %}

reports/templates/reports/main.html
{% extends "base.html" %}
<!-- Add title -->
{% block title %} reports {% endblock title %}

<!-- Add block content -->

{% block content %} reports
<hr />
{% for obj in object_list %} {{obj.name}}<br />
<div class="card mb-3">
  {% if obj.image %}
  <img src="{{obj.image.url}}" class="card-img-top" alt="{{obj.name}}" />
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{obj.name}}</h5>
    <p class="card-text">{{obj.remarks|truncatewords:2}}</p>
    <a href="{{obj.get_absolute_url}}" class="btn btn-primary">details</a>
    <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger">pdf</a>
  </div>
</div>
{% endfor %}

<!-- End block -->
{% endblock content %}

reports/templates/reports/pdf.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <title>PDF {{obj.name}}</title>
    <style>
      .image {
        width: 100%;
        height: auto;
      }
    </style>
  </head>
  <body>
    <h1>{{obj.name}}</h1>
    <hr />
    <img src="{{obj.image.path}}" class="image" />
    <br />
    <h3>Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr />
    <p>author: <b>{{obj.author.user.username}}</b></p>
    <p>created: <b>{{obj.created}}</b></p>
  </body>
</html>